import "./globals.css";
import { Poppins } from "next/font/google";
import Header from "./components/header";
import Footer from "./components/footer";

const poppins = Poppins({ weight: ["400", "600", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`poppins.className container mx-auto px-8 bg-body`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
